### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by jameswragg** [Aaronius/penpal#45]
Realising a little late in the day that this library only supported IE 11 in the 3.x branch. I'm using the current 4.x release due to being able to apply install on an existing iframe - functionality required for my project 😫.

Before I dive in to it, is IE 11 support a matter of transpiling/polyfilling or is it entirely incompatible?

Thanks in advance

**Comment by Aaronius** [comment]
Hey @jameswragg, I haven't tried running it on IE since 3.x, so I'm not sure how far off it is. If I were to guess, there's probably very little that needs to change beyond transpilation. If you find out, I'd be interested in knowing.

I noticed a fork of Penpal that has a commit that appears to be supporting IE: https://github.com/holidaycheck/penpal/commit/116780848597a2fd5c8b856ee8e0da21ceaf64e8 By looking at the changes to the files in `src`, it looks like a couple very small tweaks.

**Comment by jameswragg** [comment]
Really useful - thank you!

**Comment by Aaronius** [comment]
@jameswragg If you've investigated this further, I'd like to hear about what you discovered.
