### ISSUE TITLE
When using penpal in react, how does the child application get the latest state when calling the parent application method?

### ISSUE THREAD

**Issue by xiaoxuehai** [Aaronius/penpal#94]
When using penpal in react, when the child application calls the parent application's method, the parent application's method cannot get the latest state. How to solve this situation?

**Comment by Aaronius** [comment]
I believe you're describing something like this: https://stackoverflow.com/questions/57847594/accessing-up-to-date-state-from-within-a-callback. Reading through that Q&A will probably help you out. Two possible solutions are:

1. Use [useRef](https://react.dev/reference/react/useRef) to create a "ref" object that you always keep updated with the latest state value.
2. Pass a function to your state setter to get the current state value. It's a little weird to call the state setter, since you're not actually trying to set the state, but it would look something like this:

```js
// Set up your state in your component
const [count, setCount] = useState(0);
```
Then, in the method exposed via Penpal:

```js
let latestCount;
setCount(value => {
  latestCount = value;
  return value;
});
return latestCount
```

Or, alternatively:

```js
return new Promise(resolve => {
  setCount(value => {
    resolve(value);
    return value;
  });
});
```

Hope that helps!

**Comment by xiaoxuehai** [comment]
> I believe you're describing something like this: https://stackoverflow.com/questions/57847594/accessing-up-to-date-state-from-within-a-callback. Reading through that Q&A will probably help you out. Two possible solutions are:
> 
> 1. Use [useRef](https://react.dev/reference/react/useRef) to create a "ref" object that you always keep updated with the latest state value.
> 2. Pass a function to your state setter to get the current state value. It's a little weird to call the state setter, since you're not actually trying to set the state, but it would look something like this:
> 
> ```js
> // Set up your state in your component
> const [count, setCount] = useState(0);
> ```
> 
> Then, in the method exposed via Penpal:
> 
> ```js
> let latestCount;
> setCount(value => {
>   latestCount = value;
>   return value;
> });
> return latestCount
> ```
> 
> Or, alternatively:
> 
> ```js
> return new Promise(resolve => {
>   setCount(value => {
>     resolve(value);
>     return value;
>   });
> });
> ```
> 
> Hope that helps!
Thanks for your reply! I have used this method to solve the problem
